Repository jonhue/acts_as_favoritor, pull requests merged in 2019-05, with the labels that each got.

#56 [#55] Enable auto merge
  .automerge.yml
Labels: automerge, enhancement

#59 [#57] Release 2.1.2
  Gemfile.lock
  lib/acts_as_favoritor/version.rb
Labels: automerge

#62 [#20] Remove .rubocop_todo.yml
  .rubocop.yml
  .rubocop_todo.yml
  README.md
  lib/acts_as_favoritor/favoritable.rb
  lib/acts_as_favoritor/favoritor.rb
  lib/acts_as_favoritor/favoritor_lib.rb
  spec/factories/composers.rb
  spec/integration/acts_as_favoritable_spec.rb
  spec/integration/acts_as_favoritor_spec.rb
Labels: automerge, enhancement

#65 [#64] Release 3.0.0
  Gemfile.lock
  lib/acts_as_favoritor/version.rb
Labels: automerge

#66 [#63] Write unit tests
  README.md
  lib/acts_as_favoritor/configuration.rb
  lib/acts_as_favoritor/favoritable.rb
  lib/acts_as_favoritor/favorite_scopes.rb
  lib/acts_as_favoritor/favoritor.rb
  lib/acts_as_favoritor/favoritor_lib.rb
  lib/generators/templates/initializer.rb
  lib/generators/templates/migration.rb.erb
  lib/generators/templates/model.rb
  spec/integration/acts_as_favoritable_spec.rb
  spec/integration/acts_as_favoritor_spec.rb
  spec/lib/acts_as_favoritor/configuration_spec.rb
  spec/lib/acts_as_favoritor/favoritable_spec.rb
  spec/lib/acts_as_favoritor/favorite_scopes_spec.rb
  spec/lib/acts_as_favoritor/favoritor_lib_spec.rb
  spec/lib/acts_as_favoritor/favoritor_spec.rb
  spec/support/rails_app/app/models/composer.rb
  spec/support/rails_app/app/models/favorite.rb
Labels: automerge, enhancement

#68 [#67] Release 4.0.0
  Gemfile.lock
  lib/acts_as_favoritor/version.rb
Labels: automerge

#70 [#69] Fix readme
  README.md
Labels: automerge, bug

#72 [#71] undefined local variable or method `scope` when cache is used
  lib/acts_as_favoritor/favoritor.rb
Labels: automerge, bug

#74 [#73] Release 4.0.1
  .travis.yml
  Gemfile.lock
  lib/acts_as_favoritor/version.rb
Labels: automerge

#78 [#77] Undefined local variable or method `favoritable' when using caching
  lib/acts_as_favoritor/favoritor.rb
Labels: automerge, bug

#81 [#80] Remove mention of `:limit` and `:order` parameters from readme
  README.md
Labels: automerge, bug

#82 [#79] favorited_by_type and return type
  Gemfile.lock
  README.md
  acts_as_favoritor.gemspec
  lib/acts_as_favoritor/favoritable.rb
  lib/acts_as_favoritor/favoritor.rb
  spec/lib/acts_as_favoritor/favoritable_spec.rb
  spec/lib/acts_as_favoritor/favoritor_spec.rb
  spec/spec_helper.rb
Labels: bug

#84 [#83] Release 4.0.2
  Gemfile.lock
  lib/acts_as_favoritor/version.rb
Labels: automerge

#86 [#85] Fix auto merge
  .automerge.yml
  .github/auto-merge.yml
Labels: bug, merge
